// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package unicode

import "internal/unicodelite"

// Version is the Unicode edition from which the tables are derived.
const Version = "13.0.0"

// Categories is the set of Unicode category tables.
var Categories = map[string]*RangeTable{
	"C":  unicodelite.C,
	"Cc": unicodelite.Cc,
	"Cf": unicodelite.Cf,
	"Co": unicodelite.Co,
	"Cs": unicodelite.Cs,
	"L":  unicodelite.L,
	"Ll": unicodelite.Ll,
	"Lm": unicodelite.Lm,
	"Lo": unicodelite.Lo,
	"Lt": unicodelite.Lt,
	"Lu": unicodelite.Lu,
	"M":  unicodelite.M,
	"Mc": unicodelite.Mc,
	"Me": unicodelite.Me,
	"Mn": unicodelite.Mn,
	"N":  unicodelite.N,
	"Nd": unicodelite.Nd,
	"Nl": unicodelite.Nl,
	"No": unicodelite.No,
	"P":  unicodelite.P,
	"Pc": unicodelite.Pc,
	"Pd": unicodelite.Pd,
	"Pe": unicodelite.Pe,
	"Pf": unicodelite.Pf,
	"Pi": unicodelite.Pi,
	"Po": unicodelite.Po,
	"Ps": unicodelite.Ps,
	"S":  unicodelite.S,
	"Sc": unicodelite.Sc,
	"Sk": unicodelite.Sk,
	"Sm": unicodelite.Sm,
	"So": unicodelite.So,
	"Z":  unicodelite.Z,
	"Zl": unicodelite.Zl,
	"Zp": unicodelite.Zp,
	"Zs": unicodelite.Zs,
}

var Other = unicodelite.Other
var C = unicodelite.C
var Cc = unicodelite.Cc
var Cf = unicodelite.Cf
var Co = unicodelite.Co
var Cs = unicodelite.Cs
var Letter = unicodelite.Letter
var L = unicodelite.L
var Lower = unicodelite.Lower
var Ll = unicodelite.Ll
var Lm = unicodelite.Lm
var Lo = unicodelite.Lo
var Title = unicodelite.Title
var Lt = unicodelite.Lt
var Upper = unicodelite.Upper
var Lu = unicodelite.Lu
var Mark = unicodelite.Mark
var M = unicodelite.M
var Mc = unicodelite.Mc
var Me = unicodelite.Me
var Mn = unicodelite.Mn
var Number = unicodelite.Number
var N = unicodelite.N
var Digit = unicodelite.Digit
var Nd = unicodelite.Nd
var Nl = unicodelite.Nl
var No = unicodelite.No
var Punct = unicodelite.Punct
var P = unicodelite.P
var Pc = unicodelite.Pc
var Pd = unicodelite.Pd
var Pe = unicodelite.Pe
var Pf = unicodelite.Pf
var Pi = unicodelite.Pi
var Po = unicodelite.Po
var Ps = unicodelite.Ps
var Symbol = unicodelite.Symbol
var S = unicodelite.S
var Sc = unicodelite.Sc
var Sk = unicodelite.Sk
var Sm = unicodelite.Sm
var So = unicodelite.So
var Space = unicodelite.Space
var Z = unicodelite.Z
var Zl = unicodelite.Zl
var Zp = unicodelite.Zp
var Zs = unicodelite.Zs

// Scripts is the set of Unicode script tables.
var Scripts = map[string]*RangeTable{
	"Adlam":                  unicodelite.Adlam,
	"Ahom":                   unicodelite.Ahom,
	"Anatolian_Hieroglyphs":  unicodelite.Anatolian_Hieroglyphs,
	"Arabic":                 unicodelite.Arabic,
	"Armenian":               unicodelite.Armenian,
	"Avestan":                unicodelite.Avestan,
	"Balinese":               unicodelite.Balinese,
	"Bamum":                  unicodelite.Bamum,
	"Bassa_Vah":              unicodelite.Bassa_Vah,
	"Batak":                  unicodelite.Batak,
	"Bengali":                unicodelite.Bengali,
	"Bhaiksuki":              unicodelite.Bhaiksuki,
	"Bopomofo":               unicodelite.Bopomofo,
	"Brahmi":                 unicodelite.Brahmi,
	"Braille":                unicodelite.Braille,
	"Buginese":               unicodelite.Buginese,
	"Buhid":                  unicodelite.Buhid,
	"Canadian_Aboriginal":    unicodelite.Canadian_Aboriginal,
	"Carian":                 unicodelite.Carian,
	"Caucasian_Albanian":     unicodelite.Caucasian_Albanian,
	"Chakma":                 unicodelite.Chakma,
	"Cham":                   unicodelite.Cham,
	"Cherokee":               unicodelite.Cherokee,
	"Chorasmian":             unicodelite.Chorasmian,
	"Common":                 unicodelite.Common,
	"Coptic":                 unicodelite.Coptic,
	"Cuneiform":              unicodelite.Cuneiform,
	"Cypriot":                unicodelite.Cypriot,
	"Cyrillic":               unicodelite.Cyrillic,
	"Deseret":                unicodelite.Deseret,
	"Devanagari":             unicodelite.Devanagari,
	"Dives_Akuru":            unicodelite.Dives_Akuru,
	"Dogra":                  unicodelite.Dogra,
	"Duployan":               unicodelite.Duployan,
	"Egyptian_Hieroglyphs":   unicodelite.Egyptian_Hieroglyphs,
	"Elbasan":                unicodelite.Elbasan,
	"Elymaic":                unicodelite.Elymaic,
	"Ethiopic":               unicodelite.Ethiopic,
	"Georgian":               unicodelite.Georgian,
	"Glagolitic":             unicodelite.Glagolitic,
	"Gothic":                 unicodelite.Gothic,
	"Grantha":                unicodelite.Grantha,
	"Greek":                  unicodelite.Greek,
	"Gujarati":               unicodelite.Gujarati,
	"Gunjala_Gondi":          unicodelite.Gunjala_Gondi,
	"Gurmukhi":               unicodelite.Gurmukhi,
	"Han":                    unicodelite.Han,
	"Hangul":                 unicodelite.Hangul,
	"Hanifi_Rohingya":        unicodelite.Hanifi_Rohingya,
	"Hanunoo":                unicodelite.Hanunoo,
	"Hatran":                 unicodelite.Hatran,
	"Hebrew":                 unicodelite.Hebrew,
	"Hiragana":               unicodelite.Hiragana,
	"Imperial_Aramaic":       unicodelite.Imperial_Aramaic,
	"Inherited":              unicodelite.Inherited,
	"Inscriptional_Pahlavi":  unicodelite.Inscriptional_Pahlavi,
	"Inscriptional_Parthian": unicodelite.Inscriptional_Parthian,
	"Javanese":               unicodelite.Javanese,
	"Kaithi":                 unicodelite.Kaithi,
	"Kannada":                unicodelite.Kannada,
	"Katakana":               unicodelite.Katakana,
	"Kayah_Li":               unicodelite.Kayah_Li,
	"Kharoshthi":             unicodelite.Kharoshthi,
	"Khitan_Small_Script":    unicodelite.Khitan_Small_Script,
	"Khmer":                  unicodelite.Khmer,
	"Khojki":                 unicodelite.Khojki,
	"Khudawadi":              unicodelite.Khudawadi,
	"Lao":                    unicodelite.Lao,
	"Latin":                  unicodelite.Latin,
	"Lepcha":                 unicodelite.Lepcha,
	"Limbu":                  unicodelite.Limbu,
	"Linear_A":               unicodelite.Linear_A,
	"Linear_B":               unicodelite.Linear_B,
	"Lisu":                   unicodelite.Lisu,
	"Lycian":                 unicodelite.Lycian,
	"Lydian":                 unicodelite.Lydian,
	"Mahajani":               unicodelite.Mahajani,
	"Makasar":                unicodelite.Makasar,
	"Malayalam":              unicodelite.Malayalam,
	"Mandaic":                unicodelite.Mandaic,
	"Manichaean":             unicodelite.Manichaean,
	"Marchen":                unicodelite.Marchen,
	"Masaram_Gondi":          unicodelite.Masaram_Gondi,
	"Medefaidrin":            unicodelite.Medefaidrin,
	"Meetei_Mayek":           unicodelite.Meetei_Mayek,
	"Mende_Kikakui":          unicodelite.Mende_Kikakui,
	"Meroitic_Cursive":       unicodelite.Meroitic_Cursive,
	"Meroitic_Hieroglyphs":   unicodelite.Meroitic_Hieroglyphs,
	"Miao":                   unicodelite.Miao,
	"Modi":                   unicodelite.Modi,
	"Mongolian":              unicodelite.Mongolian,
	"Mro":                    unicodelite.Mro,
	"Multani":                unicodelite.Multani,
	"Myanmar":                unicodelite.Myanmar,
	"Nabataean":              unicodelite.Nabataean,
	"Nandinagari":            unicodelite.Nandinagari,
	"New_Tai_Lue":            unicodelite.New_Tai_Lue,
	"Newa":                   unicodelite.Newa,
	"Nko":                    unicodelite.Nko,
	"Nushu":                  unicodelite.Nushu,
	"Nyiakeng_Puachue_Hmong": unicodelite.Nyiakeng_Puachue_Hmong,
	"Ogham":                  unicodelite.Ogham,
	"Ol_Chiki":               unicodelite.Ol_Chiki,
	"Old_Hungarian":          unicodelite.Old_Hungarian,
	"Old_Italic":             unicodelite.Old_Italic,
	"Old_North_Arabian":      unicodelite.Old_North_Arabian,
	"Old_Permic":             unicodelite.Old_Permic,
	"Old_Persian":            unicodelite.Old_Persian,
	"Old_Sogdian":            unicodelite.Old_Sogdian,
	"Old_South_Arabian":      unicodelite.Old_South_Arabian,
	"Old_Turkic":             unicodelite.Old_Turkic,
	"Oriya":                  unicodelite.Oriya,
	"Osage":                  unicodelite.Osage,
	"Osmanya":                unicodelite.Osmanya,
	"Pahawh_Hmong":           unicodelite.Pahawh_Hmong,
	"Palmyrene":              unicodelite.Palmyrene,
	"Pau_Cin_Hau":            unicodelite.Pau_Cin_Hau,
	"Phags_Pa":               unicodelite.Phags_Pa,
	"Phoenician":             unicodelite.Phoenician,
	"Psalter_Pahlavi":        unicodelite.Psalter_Pahlavi,
	"Rejang":                 unicodelite.Rejang,
	"Runic":                  unicodelite.Runic,
	"Samaritan":              unicodelite.Samaritan,
	"Saurashtra":             unicodelite.Saurashtra,
	"Sharada":                unicodelite.Sharada,
	"Shavian":                unicodelite.Shavian,
	"Siddham":                unicodelite.Siddham,
	"SignWriting":            unicodelite.SignWriting,
	"Sinhala":                unicodelite.Sinhala,
	"Sogdian":                unicodelite.Sogdian,
	"Sora_Sompeng":           unicodelite.Sora_Sompeng,
	"Soyombo":                unicodelite.Soyombo,
	"Sundanese":              unicodelite.Sundanese,
	"Syloti_Nagri":           unicodelite.Syloti_Nagri,
	"Syriac":                 unicodelite.Syriac,
	"Tagalog":                unicodelite.Tagalog,
	"Tagbanwa":               unicodelite.Tagbanwa,
	"Tai_Le":                 unicodelite.Tai_Le,
	"Tai_Tham":               unicodelite.Tai_Tham,
	"Tai_Viet":               unicodelite.Tai_Viet,
	"Takri":                  unicodelite.Takri,
	"Tamil":                  unicodelite.Tamil,
	"Tangut":                 unicodelite.Tangut,
	"Telugu":                 unicodelite.Telugu,
	"Thaana":                 unicodelite.Thaana,
	"Thai":                   unicodelite.Thai,
	"Tibetan":                unicodelite.Tibetan,
	"Tifinagh":               unicodelite.Tifinagh,
	"Tirhuta":                unicodelite.Tirhuta,
	"Ugaritic":               unicodelite.Ugaritic,
	"Vai":                    unicodelite.Vai,
	"Wancho":                 unicodelite.Wancho,
	"Warang_Citi":            unicodelite.Warang_Citi,
	"Yezidi":                 unicodelite.Yezidi,
	"Yi":                     unicodelite.Yi,
	"Zanabazar_Square":       unicodelite.Zanabazar_Square,
}

// Properties is the set of Unicode property tables.
var Properties = map[string]*RangeTable{
	"ASCII_Hex_Digit":                    unicodelite.ASCII_Hex_Digit,
	"Bidi_Control":                       unicodelite.Bidi_Control,
	"Dash":                               unicodelite.Dash,
	"Deprecated":                         unicodelite.Deprecated,
	"Diacritic":                          unicodelite.Diacritic,
	"Extender":                           unicodelite.Extender,
	"Hex_Digit":                          unicodelite.Hex_Digit,
	"Hyphen":                             unicodelite.Hyphen,
	"IDS_Binary_Operator":                unicodelite.IDS_Binary_Operator,
	"IDS_Trinary_Operator":               unicodelite.IDS_Trinary_Operator,
	"Ideographic":                        unicodelite.Ideographic,
	"Join_Control":                       unicodelite.Join_Control,
	"Logical_Order_Exception":            unicodelite.Logical_Order_Exception,
	"Noncharacter_Code_Point":            unicodelite.Noncharacter_Code_Point,
	"Other_Alphabetic":                   unicodelite.Other_Alphabetic,
	"Other_Default_Ignorable_Code_Point": unicodelite.Other_Default_Ignorable_Code_Point,
	"Other_Grapheme_Extend":              unicodelite.Other_Grapheme_Extend,
	"Other_ID_Continue":                  unicodelite.Other_ID_Continue,
	"Other_ID_Start":                     unicodelite.Other_ID_Start,
	"Other_Lowercase":                    unicodelite.Other_Lowercase,
	"Other_Math":                         unicodelite.Other_Math,
	"Other_Uppercase":                    unicodelite.Other_Uppercase,
	"Pattern_Syntax":                     unicodelite.Pattern_Syntax,
	"Pattern_White_Space":                unicodelite.Pattern_White_Space,
	"Prepended_Concatenation_Mark":       unicodelite.Prepended_Concatenation_Mark,
	"Quotation_Mark":                     unicodelite.Quotation_Mark,
	"Radical":                            unicodelite.Radical,
	"Regional_Indicator":                 unicodelite.Regional_Indicator,
	"Sentence_Terminal":                  unicodelite.Sentence_Terminal,
	"STerm":                              unicodelite.Sentence_Terminal,
	"Soft_Dotted":                        unicodelite.Soft_Dotted,
	"Terminal_Punctuation":               unicodelite.Terminal_Punctuation,
	"Unified_Ideograph":                  unicodelite.Unified_Ideograph,
	"Variation_Selector":                 unicodelite.Variation_Selector,
	"White_Space":                        unicodelite.White_Space,
}

// FoldCategory maps a category name to a table of
// code points outside the category that are equivalent under
// simple case folding to code points inside the category.
// If there is no entry for a category name, there are no such points.
var FoldCategory = map[string]*RangeTable{
	"L":  unicodelite.FoldL,
	"Ll": unicodelite.FoldLl,
	"Lt": unicodelite.FoldLt,
	"Lu": unicodelite.FoldLu,
	"M":  unicodelite.FoldM,
	"Mn": unicodelite.FoldMn,
}

// FoldScript maps a script name to a table of
// code points outside the script that are equivalent under
// simple case folding to code points inside the script.
// If there is no entry for a script name, there are no such points.
var FoldScript = map[string]*RangeTable{
	"Common":    unicodelite.FoldCommon,
	"Greek":     unicodelite.FoldGreek,
	"Inherited": unicodelite.FoldInherited,
}
