name: Build toolchain

permissions:
  contents: write

on:
  push:
    branches:
      - tailscale
      - 'tailscale.go1.19'
      - 'tailscale.go1.20'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: cd src && ./all.bash

  linux:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: cd src && ./make.bash
    - name: trim unnecessary bits
      run: |
        rm -rf pkg/*_*
        find . -type d -name 'testdata' -print0 | xargs -0 rm -rf
        find . -name '*_test.go' -delete
    - name: archive
      run: cd .. && tar --exclude-vcs -zcf linux.tar.gz go
    - name: save
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: ../linux.tar.gz

  linux-static:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: cd src && ./make.bash
      env:
        CGO_ENABLED: "0"
    - name: trim unnecessary bits
      run: |
        rm -rf pkg/*_*
        find . -type d -name 'testdata' -print0 | xargs -0 rm -rf
        find . -name '*_test.go' -delete
    - name: archive
      run: cd .. && tar --exclude-vcs -zcf linux-static.tar.gz go
    - name: save
      uses: actions/upload-artifact@v1
      with:
        name: linux-static
        path: ../linux-static.tar.gz

  darwin:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: cd src && ./make.bash
      env:
        GOOS: darwin
    - name: trim unnecessary bits
      run: |
        rm -rf pkg/*_* pkg/tool/linux_amd64 bin/go bin/gofmt
        mv bin/darwin_amd64/* bin/
        find . -type d -name 'testdata' -print0 | xargs -0 rm -rf
        find . -name '*_test.go' -delete
    - name: archive
      run: cd .. && tar --exclude-vcs -zcf darwin.tar.gz go
    - name: save
      uses: actions/upload-artifact@v1
      with:
        name: darwin
        path: ../darwin.tar.gz

  linux-arm64:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: cd src && ./make.bash
      env:
        GOOS: linux
        GOARCH: arm64
    - name: trim unnecessary bits
      run: |
        rm -rf pkg/*_* pkg/tool/linux_amd64 bin/go bin/gofmt
        mv bin/linux_arm64/* bin/
        find . -type d -name 'testdata' -print0 | xargs -0 rm -rf
        find . -name '*_test.go' -delete
    - name: archive
      run: cd .. && tar --exclude-vcs -zcf linux-arm64.tar.gz go
    - name: save
      uses: actions/upload-artifact@v1
      with:
        name: linux-arm64
        path: ../linux-arm64.tar.gz


  darwin-arm64:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: cd src && ./make.bash
      env:
        GOOS: darwin
        GOARCH: arm64
    - name: trim unnecessary bits
      run: |
        rm -rf pkg/*_* pkg/tool/linux_amd64 bin/go bin/gofmt
        mv bin/darwin_arm64/* bin/
        find . -type d -name 'testdata' -print0 | xargs -0 rm -rf
        find . -name '*_test.go' -delete
    - name: archive
      run: cd .. && tar --exclude-vcs -zcf darwin-arm64.tar.gz go
    - name: save
      uses: actions/upload-artifact@v1
      with:
        name: darwin-arm64
        path: ../darwin-arm64.tar.gz


  release:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    needs: [test, linux, linux-static, darwin, darwin-arm64, linux-arm64]
    steps:
    - name: download linux
      uses: actions/download-artifact@v1
      with:
        name: linux
    - name: download linux-static
      uses: actions/download-artifact@v1
      with:
        name: linux-static
    - name: download darwin
      uses: actions/download-artifact@v1
      with:
        name: darwin
    - name: download darwin-arm64
      uses: actions/download-artifact@v1
      with:
        name: darwin-arm64
    - name: download linux-arm64
      uses: actions/download-artifact@v1
      with:
        name: linux-arm64
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Release name can't be the same as tag name, sigh
        tag_name: build-${{ github.sha }}
        release_name: ${{ github.sha }}
        draft: false
        prerelease: true
    - name: upload linux tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: linux/linux.tar.gz
        asset_name: linux.tar.gz
        asset_content_type: application/gzip
    - name: upload linux-static tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: linux-static/linux-static.tar.gz
        asset_name: linux-static.tar.gz
        asset_content_type: application/gzip
    - name: upload linux-arm64 tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: linux-arm64/linux-arm64.tar.gz
        asset_name: linux-arm64.tar.gz
        asset_content_type: application/gzip
    - name: upload darwin tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: darwin/darwin.tar.gz
        asset_name: darwin.tar.gz
        asset_content_type: application/gzip
    - name: upload darwin-arm64 tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: darwin-arm64/darwin-arm64.tar.gz
        asset_name: darwin-arm64.tar.gz
        asset_content_type: application/gzip
    - name: checkout
      uses: actions/checkout@v2
    - name: Delete older builds
      run: ./.github/workflows/prune_old_builds.sh "${{ secrets.GITHUB_TOKEN }}"
